name: CI with Maven

on:
  push:
    branches:
      - main  # or any branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: cd 01-sb-sbdata-curd-repo-app && mvn clean install

      - name: Run tests
        run: mvn test
